remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Amrutha Garimella
description: Data Analyst skilled in SQL, Python, Excel, and Power BI, focused on turning raw data into accurate, actionable business insights.
